function post_install(){
	_info "Made with love by Kimiblock Moe⭐"
	/usr/bin/moeRelease
	systemctl enable linux-modules-cleanup.service
	_info "Install qadwaitaplatform-qt5-git in the AUR to get libadwaita style CSD in Qt"
	if [[ $(pacman -Q) =~ gnome-shell-performance ]] & [[ $(pacman -Q) =~ mutter-performance ]]; then
		_info "rt scheduler for mutter is enabled"
	else
		_info "Install gnome-shell-performance and mutter-performance then rebuild this package to get better performance and rt schedulers"
	fi
	_info "Signing EFI binaries"
	if [[ $(paru -Q) =~ "gnome-shell" ]]; then
		_info "Warning! This package is not compatible with Gnome, please set environment variable GTK_USE_PORTAL=0!"
	fi
	sbctl sign -s "/efi/EFI/Boot/BOOTx64.efi"
}

function _info() {
	if [ -f /usr/bin/pamac ]; then
		echo "  ==> [Info]: $@"
	else
		all_off="$(tput sgr0)"
		bold="${all_off}$(tput bold)"
		blue="${bold}$(tput setaf 4)"
		yellow="${bold}$(tput setaf 3)"
		printf "${blue}==>${yellow} [Info]:${bold} $1${all_off}\n"
	fi
}

function post_upgrade(){
    post_install
}

