function post_install(){
    _info "Made with love by Kimiblock Moe⭐"
    /usr/bin/moeRelease
    systemctl enable linux-modules-cleanup.service
}

function _info() {
	if [ -f /usr/bin/pamac ]; then
		echo "  ==> [Info]: $@"
	else
		all_off="$(tput sgr0)"
		bold="${all_off}$(tput bold)"
		blue="${bold}$(tput setaf 4)"
		yellow="${bold}$(tput setaf 3)"
		printf "${blue}==>${yellow} [Info]:${bold} $1${all_off}\n"
    fi
}

function post_upgrade(){
    post_install
}

