function post_install(){
	_info "Made with love by Kimiblock Moe⭐"
	/usr/bin/moeRelease
	systemctl enable linux-modules-cleanup.service
	_info "Install qadwaitaplatform-qt5-git in the AUR to get libadwaita style CSD in Qt"
	if [[ $(pacman -Q) =~ gnome-shell-performance ]] & [[ $(pacman -Q) =~ mutter-performance ]]; then
		_info "rt scheduler for mutter is enabled"
	else
		_info "Install gnome-shell-performance and mutter-performance then rebuild this package to get better performance and rt schedulers"
	fi
	_info "Signing EFI binaries"
	sbctl sign -s "/efi/EFI/Boot/BOOTx64.efi"
	flatpak mask 'org.freedesktop.Platform.GL32.nvidia*'
	flatpak mask 'org.freedesktop.Platform.GL.nvidia*'
	flatpak override --unset-env=__EGL_VENDOR_LIBRARY_FILENAMES
	flatpak override --unset-env=VK_ICD_FILENAMES
	flatpak override --unset-env=QT_QPA_PLATFORMTHEME
	flatpak override --filesystem=xdg-config/fontconfig:ro
	flatpak override --filesystem=xdg-config/Kvantum:ro
	flatpak override --device=dri
	flatpak override --filesystem=xdg-config/gtk-3.0:ro
	flatpak override --filesystem=xdg-config/gtk-4.0:ro
}

function _info() {
	if [ -f /usr/bin/pamac ]; then
		echo "  ==> [Info]: $@"
	else
		all_off="$(tput sgr0)"
		bold="${all_off}$(tput bold)"
		blue="${bold}$(tput setaf 4)"
		yellow="${bold}$(tput setaf 3)"
		printf "${blue}==>${yellow} [Info]:${bold} $1${all_off}\n"
	fi
}

function post_upgrade(){
    post_install
}

